image: python:3.5

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: cityhuntdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: supersecret
  POSTGRES_HOST_AUTH_METHOD: trust
  DB_STRING: "postgres://$POSTGRES_USER@postgres:5433/$POSTGRES_DB"

before_script:
    - date
    - uname -a
    - cd flask-backend
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - printenv | sort

stages:
   - Tests

test:
  stage: Tests
  script:
  - python tests.py
  only:
  - merge_requests
  - master
  - dev
  - yuls_dev