runtime: python37
env: flex
entrypoint: gunicorn -b :$PORT main:app

env_variables:
    # postgresql+psycopg2://USER:PASSWORD@/DATABASE?host=/cloudsql/INSTANCE_CONNECTION_NAME
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    DB_STRING: >-
      postgresql+psycopg2://postgres:zxcvbn12@/postgres?host=/cloudsql/city-hunt-267820:us-central1:database-city-hunt

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: city-hunt-267820:us-central1:database-city-hunt

instance_class: F1
automatic_scaling:
  max_instances: 1